// Single source of truth for NAP and brand-level facts.
// Import from anywhere via `@/config/business`.

export const BUSINESS = {
  name: "Birmingham Removals",
  legalName: "Birmingham Removals",
  url: "https://www.birminghamremovals.uk",
  logo: "https://www.birminghamremovals.uk/images/logo.webp",
  ogImage: "https://www.birminghamremovals.uk/og-image.jpg",
  phoneDisplay: "07365 380090",
  phoneE164: "+447365380090",
  telHref: "tel:+447365380090",
  email: "hello@birminghamremovals.uk",
  priceRange: "££",
  foundingYear: 2015,
  rating: { value: "4.9", count: "312" },
  address: {
    locality: "Birmingham",
    region: "West Midlands",
    country: "GB",
  },
  areasServed: [
    "Birmingham",
    "Solihull",
    "Sutton Coldfield",
    "Edgbaston",
    "Harborne",
    "Selly Oak",
    "Moseley",
    "Kings Heath",
    "Erdington",
    "Hall Green",
    "Northfield",
    "Acocks Green",
    "Bearwood",
    "City Centre",
    "Coventry",
    "Dudley",
    "Great Barr",
    "Handsworth",
    "Kings Norton",
    "Quinton",
    "West Bromwich",
    "Wolverhampton",
    "West Midlands",
  ],
  // Add real social URLs as they go live — empty array means no `sameAs` is emitted.
  sameAs: [],
};
